# Generated by Django 5.2.1 on 2025-05-27 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título descriptivo del audio', max_length=255)),
                ('file', models.FileField(help_text='Ruta al archivo MP3', upload_to='audios/')),
                ('metadata', models.JSONField(blank=True, help_text='Metadatos generales en formato JSON', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.FloatField(help_text='Tiempo de inicio en segundos')),
                ('end', models.FloatField(help_text='Tiempo de fin en segundos')),
                ('text', models.TextField(blank=True, help_text='Texto original de la transcripción')),
                ('words', models.JSONField(help_text='Lista de palabras con timestamps, probabilidad y flag de revisión')),
                ('fills', models.JSONField(blank=True, help_text='Correcciones por palabra en formato JSON {index: palabra}', null=True)),
                ('free_text', models.TextField(blank=True, help_text='Transcripción libre ingresada por el usuario', null=True)),
                ('revisado', models.BooleanField(default=False, help_text='Marca si el segmento fue revisado')),
                ('version', models.PositiveIntegerField(default=1, help_text='Versión de la revisión')),
                ('locked_at', models.DateTimeField(blank=True, help_text='Fecha y hora del bloqueo', null=True)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='review.audio')),
                ('locked_by', models.ForeignKey(blank=True, help_text='Usuario que actualmente bloqueó el segmento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_segments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['audio', 'start'],
                'unique_together': {('audio', 'start', 'end')},
            },
        ),
    ]
